### ISSUE TITLE
Getting duplicate key value on fresh install

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1671]
Package version (if known): v9.0.1

## Describe the bug
Running `invenio-cli services setup --no-demo-data` followed by `invenio-cli run` in a brand new (not our instance, just a new from scratch instance), returns for many records (not all)  

```
[SQL: INSERT INTO pidstore_pid (created, updated, pid_type, pid_value, pid_provider, status, object_type, object_uuid) VALUES (%(created)s, %(updated)s, %(pid_type)s, %(pid_value)s, %(pid_provider)s, %(status)s, %(object_type)s, %(object_uuid)s) RETURNING pidstore_pid.id]
[parameters: {'created': datetime.datetime(2022, 5, 27, 17, 24, 43, 452371), 'updated': datetime.datetime(2022, 5, 27, 17, 24, 43, 452375), 'pid_type': 'ttyp', 'pid_value': 'alternative-title', 'pid_provider': None, 'status': 'R', 'object_type': 'rec', 'object_uuid': UUID('b950a83e-d244-4411-89d5-001d2cedabf2')}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2022-05-27 13:24:43,455: ERROR/ForkPoolWorker-6] Task invenio_rdm_records.fixtures.tasks.create_vocabulary_record[98a628a5-615a-4ca6-9c4d-d5c9131fe13a] raised unexpected: PersistentIdentifierError()
Traceback (most recent call last):
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/flask_celeryext/app.py", line 70, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_rdm_records/fixtures/tasks.py", line 45, in create_vocabulary_record
    service.create(system_identity, data)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 327, in inner
    res = f(self, *args, **kwargs)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 278, in create
    return self._create(self.record_cls, identity, data, uow=uow,
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 331, in inner
    return f(self, *args, **kwargs)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 305, in _create
    self.run_components(
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_records_resources/services/base/service.py", line 72, in run_components
    getattr(component, action)(*args, **kwargs)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_vocabularies/services/components.py", line 51, in create
    self.service.record_cls.pid.create(record)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_vocabularies/records/systemfields/pid.py", line 59, in create
    return self.field.create(record)
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_records_resources/records/systemfields/pid.py", line 119, in create
    pid = self._provider.create(
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_vocabularies/records/pidprovider.py", line 55, in create
    return super().create(
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_pidstore/providers/base.py", line 46, in create
    pid = PersistentIdentifier.create(
  File "/home/guillaume/dev/or_2022_customization/my-site/.venv/lib/python3.8/site-packages/invenio_pidstore/models.py", line 163, in create
    raise PIDAlreadyExists(pid_type=pid_type, pid_value=pid_value)
invenio_pidstore.errors.PersistentIdentifierError
```
by the worker.

The application works (so far at time of writing), but these errors are alarming.

**Comment by Samk13** [comment]
Try `invenio-cli services setup --no-demo-data --force`
