### ISSUE TITLE
communities: id type mismatch

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#1699]
spotted on inveniordm.web.cern.ch,please investigate the reason (v9.0.0)

```
[2022-06-03 12:14:53,483] ERROR in app: Exception on /communities [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/usr/local/lib/python3.8/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/resources/records/resource.py", line 93, in create
    item = self.service.create(
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 327, in inner
    res = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 278, in create
    return self._create(self.record_cls, identity, data, uow=uow,
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 331, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 293, in _create
    data, errors = self.schema.load(
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/records/schema.py", line 81, in load
    valid_data = self.schema(context=context, **schema_args).load(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 368, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 669, in _deserialize
    return self._load(value, data, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 652, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 368, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 669, in _deserialize
    return self._load(value, data, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 652, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 851, in _do_load
    processed_data = self._invoke_load_processors(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 1095, in _invoke_load_processors
    data = self._invoke_processors(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 1225, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_communities/communities/schema.py", line 80, in clean
    data.pop(name, None)
AttributeError: 'str' object has no attribute 'pop'
[pid: 115201|app: 0|req: 1446/17398] 10.76.39.29 () {62 vars in 1262 bytes} [Fri Jun  3 12:14:53 2022] POST /api/communities => generated 182 bytes in 151 msecs (HTTP/1.1 500) 14 headers in 578 bytes (1 switches on core 0)
[2022-06-03 12:15:02,487] ERROR in app: Exception on /communities [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/usr/local/lib/python3.8/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/resources/records/resource.py", line 93, in create
    item = self.service.create(
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 327, in inner
    res = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 278, in create
    return self._create(self.record_cls, identity, data, uow=uow,
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 331, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 293, in _create
    data, errors = self.schema.load(
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/records/schema.py", line 81, in load
    valid_data = self.schema(context=context, **schema_args).load(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 368, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 669, in _deserialize
    return self._load(value, data, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 652, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 368, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 669, in _deserialize
    return self._load(value, data, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/fields.py", line 652, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 851, in _do_load
    processed_data = self._invoke_load_processors(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 1095, in _invoke_load_processors
    data = self._invoke_processors(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 1225, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_communities/communities/schema.py", line 80, in clean
    data.pop(name, None)
AttributeError: 'str' object has no attribute 'pop'
```

**Comment by Samk13** [comment]
I produced this one 😀🙋‍♂️ in short, we need to update the documentation for REST API and better error handling for invalid JSON body 
Full conversation for this bug on [Discord](https://discord.com/channels/692989811736182844/704625518552547329/982228002870018109)
