### ISSUE TITLE
files: unicode in filenames causing errors

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/invenio-app-rdm#1744]
Package version (if known): 9.0 and earlier

## Describe the bug

Files with unicode in filenames will not upload. If a user fails to notice the upload has failed and requests a review, the record gets stuck in an unreviewable/undeleteable state. 

I originally reported this here: https://github.com/inveniosoftware/react-invenio-deposit/issues/464 . But I think its a bit wider in scope so I'm opening this. The behaviour has changed slightly, and the problem can be made much worse - see steps below.

## Steps to Reproduce
1. Create a new upload
2. Add a file with the name with a unicode containing name(*), eg -'16010_Faust I Von der Gelehrtentragödie zur Hermeneutik.pdf' observed to fail. 
3. Upload fails - file is 'pending' - this is easily missed and may not be understood by the user (ie no explicit 'your upload failed' error is issued.
4. Submit draft record to community for review
5. Attempt to review - record will not render (stacktrace below) and there is no way to decline the request or delete the record
6. In a blind panic (assuming this is a live system with user training in progress...) start a dev instance on your live data with a hacked `macros/files.html` template so you can decline the record before anyone else notices (this step optional :smile:)

(*) - I suspect any unicode bearing filename causes this - I've seen it in more than 1 case. ASCII including spaces/punctuation isn't causing any problems so I guess its an issue of encoding the filename somewhere along the line? 

## Expected behavior

* Files with unicode names should upload correctly
* The issue of failed uploads preventing review template rendering may need to be addressed also - or prevent users from submitting records for review which have 'pending' files? 

## Screenshots (if applicable)

Failed upload:
![Image](https://user-images.githubusercontent.com/7934352/173788385-d92d9e35-3d08-46ee-aa1d-79c37289e6b5.png)

(this otherwise behaves like a normal upload - there's no error thrown to alert the user)

Stack trace when trying to review record with 'pending' / failed file:

[2022-06-15 07:04:49,543] ERROR in app: Exception on /communities/iib1/requests/da146259-31d4-41cc-8ccb-f1b96db7377d [GET]
Traceback (most recent call last):
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_requests/views/decorators.py", line 29, in view
    return f(**kwargs)
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_communities/views/decorators.py", line 25, in view
    return f(**kwargs)
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/requests_ui/views/requests.py", line 147, in community_dashboard_request_view
    return render_template(
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html", line 13, in top-level template code
    {% set active_community_header_menu_item = 'requests' %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_requests/templates/semantic-ui/invenio_requests/details/index.html", line 62, in top-level template code
    {% block javascript %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_communities/templates/semantic-ui/invenio_communities/details/base.html", line 10, in top-level template code
    {% extends "invenio_communities/base.html" %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_communities/templates/semantic-ui/invenio_communities/base.html", line 10, in top-level template code
    {% extends config.BASE_TEMPLATE %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 72, in top-level template code
    {%- block body %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 83, in block 'body'
    {%- block body_inner %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 91, in block 'body_inner'
    {%- block page_body %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_requests/templates/semantic-ui/invenio_requests/details/index.html", line 20, in block 'page_body'
    {%- block request_body %}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/invenio_requests/templates/semantic-ui/invenio_requests/details/index.html", line 45, in block 'request_body'
    {%- block request_timeline %}
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html", line 72, in block 'request_timeline'
    {% include "invenio_app_rdm/records/detail.html" %}
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 27, in top-level template code
    {%- block page_body %}
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 133, in block 'page_body'
    {%- block record_body -%}
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 229, in block 'record_body'
    {%- block record_files -%}
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 242, in block 'record_files'
    {{ file_list_box(files, record.id, is_preview, record) }}
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/srv/rdm/kittler-texts/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html", line 106, in template
    <small class="text-muted">{% if files %} ({{files|sum(attribute='size')|filesizeformat(binary=binary_sizes)}}){% endif %}</small>
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/jinja2/async_utils.py", line 45, in wrapper
    return normal_func(*args, **kwargs)
  File "/srv/venv/kittler-texts/lib/python3.8/site-packages/jinja2/filters.py", line 1295, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]

**Comment by dfdan** [comment]
Just to add - also had a case of this today with `Europalyrik_1982_467–477.pdf`. Took a minute to spot that one.

In case github squashes it, the - is a `U+2013` - further confirms my suspicion this is anything unicode.

**Comment by alejandromumo** [comment]
The issue here lies to how client and server deal with special characters. E.g. the character `á` can be encoded as a single unicode character (`á`) or as a composite character (`a ´`). For reference:

https://javascript.info/string#diacritical-marks-and-normalization
https://stackoverflow.com/questions/16799810/seemingly-identical-strings-fail-comparison
