### ISSUE TITLE
Misspelled file names in download links lead to internal server errors (500)

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#1998]
Package version (if known): 10.0.0

## Context

We've noticed that our server sometimes produces 500 responses for file downloads, because the file names in the accessed download links are transformed to lower-case.
It seems that those requests are coming from [bing](https://www.bing.com/) bots.

## Example

The following is an example of a valid file download link: https://test.researchdata.tuwien.ac.at/records/rardm-wb730/files/lurkin.jpg?download=1

If the file name part of the URL is misspelled however (e.g. by using upper-case), it becomes invalid: https://test.researchdata.tuwien.ac.at/records/rardm-wb730/files/LURKIN.JPG?download=1

Accessing the second link results in a "500 internal server error" page, and the following stack trace on the server:
```
Exception on /records/rardm-wb730/files/LURKIN.JPG [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/decorators.py", line 79, in view
    return f(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/decorators.py", line 159, in view
    return f(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_app_rdm/records_ui/views/records.py", line 171, in record_file_download
    return file_item.send_file(as_attachment=download)
AttributeError: 'NoneType' object has no attribute 'send_file'
```

## Expected behavior

I would expect one of the two statements to be correct:
* The file name in download links is case-insensitive
* A misspelled file name in download links leads to a 404 page

IMO, the second one would be more reasonable.
I couldn't find any spot where Invenio would generate misspelled links.
It's not Invenio's fault if clients perform any kind of text manipulation on links before accessing them.

Further, we should probably add a `robots.txt` to prevent search bots from accessing file download links as well.

**Comment by max-moser** [comment]
The problem happens when the [`file_item` object](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/views/records.py#L177) in the `record_file_download` view function is set to `None`.
The object is being passed as keyword argument by the [`pass_file_item` decorator](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/views/decorators.py#L161).
This can happen if the file name isn't found in the record's file list in the [`files_service.get_file_content()`](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/files/service.py#L255-L256).

Given that there's an [error handler for `KeyError`](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/views/__init__.py#L108) defined in the blueprint, I could see two simple fixes:
* Raise a `KeyError` in the decorator or view function if the service returns `None` as file
* Have the service raise a `KeyError` if the file can't be found

The behavior for the service in the latter case could be made controllable by an argument to the method (e.g. `raise_=True`). But I have a feeling that this needs to be very well documented to not cause confusion.
We could wrap this in a custom exception, but I'm not sure if this is any better.

So I'm slightly leaning towards the first approach, probably handle it in the decorator because that's "closer" to the service call.

We should check if there's any other spots where `files_service.get_file_content()` is called but not checked for `None`.
