### ISSUE TITLE
Uploading an empty file leads to errors in UI

### ISSUE THREAD

**Issue by rekt-hard** [inveniosoftware/invenio-app-rdm#2032]
Package version (if known): invenio-app-rdm==11.0.0.dev13

## Describe the bug
When uploading a file with 0 bytes, there are display errors in the deposit UI regarding
1. size of empty file
2. total file size

Trying to view the details page results in an error.

## Steps to Reproduce
1. Create a new record
4. Upload a file with 0 bytes
5. Witness UI display errors
6. Fill in required fields
7. Publish record
8. Visit record detail page
9. Witness JinjaTemplateError

## Expected behavior
See correct total file size in deposit page.
Be able to view detail page as usual.

## Screenshots (if applicable)
Deposit page
![image](https://user-images.githubusercontent.com/72449192/213673006-315fb857-dc86-4cfb-8b86-51feb673bc77.png)

Search
![image](https://user-images.githubusercontent.com/72449192/213673249-5a48d2ee-9441-4ade-834d-e49d4c8ee0ef.png)

Detail page
![image](https://user-images.githubusercontent.com/72449192/213673344-c2c260e1-34ea-4f86-bf70-f95b505b98bf.png)

## Additional context
Stack trace:

```
Traceback (most recent call last):
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/views/decorators.py", line 79, in view
    return f(**kwargs)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/views/decorators.py", line 127, in view
    return f(**kwargs)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/views/decorators.py", line 224, in view
    return f(**kwargs)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/views/records.py", line 95, in record_detail
    return render_template(
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 344, in top-level template code
    {%- block javascript %}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 72, in top-level template code
    {%- block body %}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 83, in block 'body'
    {%- block body_inner %}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 91, in block 'body_inner'
    {%- block page_body %}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 135, in block 'page_body'
    {%- block record_body -%}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 231, in block 'record_body'
    {%- block record_files -%}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 244, in block 'record_files'
    {{ file_list_box(files, record.id, is_preview, record) }}
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html", line 106, in template
    <small class="text-muted">{% if files %} ({{files|sum(attribute='size')|filesizeformat(binary=binary_sizes)}}){% endif %}</small>
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/jinja2/async_utils.py", line 45, in wrapper
    return normal_func(*args, **kwargs)
  File "/home/david/Documents/invenio-rdm/rdm-v11-dev/env/lib/python3.10/site-packages/jinja2/filters.py", line 1295, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'size'

```

**Comment by max-moser** [comment]
That sounds a lot like the error I triggered by hitting "publish" too quickly after uploading the file.

Stack trace:
```
127.0.0.1 - - [01/Mar/2023 12:57:17] "GET /records/zgres-nmq44 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/views/decorators.py", line 82, in view
    return f(**kwargs)
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/views/decorators.py", line 130, in view
    return f(**kwargs)
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/views/decorators.py", line 227, in view
    return f(**kwargs)
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/views/records.py", line 147, in record_detail
    return render_template(
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 343, in top-level template code
    {%- block javascript %}
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 72, in top-level template code
    {%- block body %}
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 83, in block 'body'
    {%- block body_inner %}
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/invenio_theme/templates/semantic-ui/invenio_theme/page.html", line 91, in block 'body_inner'
    {%- block page_body %}
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 134, in block 'page_body'
    {%- block record_body -%}
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 230, in block 'record_body'
    {%- block record_files -%}
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html", line 243, in block 'record_files'
    {{ file_list_box(files, record.id, is_preview, record) }}
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/mmoser/rdm/modules/invenio-app-rdm/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html", line 119, in template
    <small class="text-muted">{% if files %} ({{files|sum(attribute='size')|filesizeformat(binary=binary_sizes)}}){% endif %}</small>
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/jinja2/async_utils.py", line 45, in wrapper
    return normal_func(*args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/lib/python3.9/site-packages/jinja2/filters.py", line 1295, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'size'
```

On the deposit edit page, it looks like the file upload hasn't been completed (can't delete it, etc.):
![image](https://user-images.githubusercontent.com/6437519/222144849-9cd7c110-52f2-4c65-8722-ac87327609ae.png)

The debugger shows that the file dictionary in question has everything except for a `size` attribute.
![image](https://user-images.githubusercontent.com/6437519/222144875-2ae681fb-d691-4b6c-ac9b-75a9b183124e.png)

**Comment by max-moser** [comment]
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/6437519/c4b7bb18-b694-4a9a-b254-c7b2c49724ea)
