### ISSUE TITLE
Installation Error - Containerized application @ Apple M1

### ISSUE THREAD

**Issue by steviewanders** [inveniosoftware/invenio-app-rdm#2191]
Package version (if known): 
9.1 and 11.0

## Describe the bug
I followed the instructions at https://inveniordm.docs.cern.ch/install/ and received error as below when I built the container application :

```shell
RUN cp -r ./static/. /opt/invenio/var/instance/static/ &&     cp -r ./assets/. /opt/invenio/var/instance/assets/ &&     invenio collect --verbose  &&     invenio webpack buildall:
#0 12.92 Traceback (most recent call last):
#0 12.92   File "/usr/local/bin/invenio", line 8, in <module>
#0 12.92     sys.exit(cli())
#0 12.92   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
#0 12.93     return self.main(*args, **kwargs)
#0 12.93   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
#0 12.93     rv = self.invoke(ctx)
#0 12.93   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
#0 12.93     return _process_result(sub_ctx.command.invoke(sub_ctx))
#0 12.93   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
#0 12.93     return ctx.invoke(self.callback, **ctx.params)
#0 12.93   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
#0 12.93     return __callback(*args, **kwargs)
#0 12.93   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
#0 12.93     return f(get_current_context(), *args, **kwargs)
#0 12.93   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 354, in decorator
#0 12.93     app = __ctx.ensure_object(ScriptInfo).load_app()
#0 12.93   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 301, in load_app
#0 12.93     app = self.create_app()
#0 12.93   File "/usr/local/lib/python3.9/site-packages/invenio_base/app.py", line 170, in create_cli_app
#0 12.93     app = create_app(debug=get_debug_flag())
#0 12.93   File "/usr/local/lib/python3.9/site-packages/invenio_base/app.py", line 106, in _create_app
#0 12.93     config_loader(app, **kwargs)
#0 12.93   File "/usr/local/lib/python3.9/site-packages/invenio_app/factory.py", line 60, in config_loader
#0 12.94     invenio_config_loader(app, **kwargs_config)
#0 12.94   File "/usr/local/lib/python3.9/site-packages/invenio_config/utils.py", line 54, in _config_loader
#0 12.94     InvenioConfigEntryPointModule(app=app)
#0 12.94   File "/usr/local/lib/python3.9/site-packages/invenio_config/entrypoint.py", line 35, in __init__
#0 12.94     self.init_app(app)
#0 12.94   File "/usr/local/lib/python3.9/site-packages/invenio_config/entrypoint.py", line 45, in init_app
#0 12.94     app.config.from_object(ep.load())
#0 12.94   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2516, in load
#0 12.94     self.require(*args, **kwargs)
#0 12.94   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2539, in require
#0 12.94     items = working_set.resolve(reqs, env, installer, extras=self.extras)
#0 12.94   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 827, in resolve
#0 12.94     dist = self._resolve_dist(
#0 12.94   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
#0 12.94     raise DistributionNotFound(req, requirers)
#0 12.95 pkg_resources.DistributionNotFound: The 'greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))' distribution was not found and is required by SQLAlchemy
------
failed to solve: executor failed running [/bin/sh -c cp -r ./static/. ${INVENIO_INSTANCE_PATH}/static/ &&     cp -r ./assets/. ${INVENIO_INSTANCE_PATH}/assets/ &&     invenio collect --verbose  &&     invenio webpack buildall]: exit code: 1
Failed to start containerized instance.
```

## Steps to Reproduce
1. `pip install invenio-cli (ok)`
2. `invenio-cli check-requirements --development (ok)`
```shell
invenio-cli check-requirements --development
Checking pre-requirements...
Checking Python version...
Python version OK. Got 3.9.16.
Checking Pipenv is installed...
Pipenv OK. Got version 2023.3.20.
Checking Docker version...
Docker version OK. Got 20.10.17.
Checking Docker Compose version...
Docker Compose version OK. Got 2.10.2.
Checking Node version...
Node version OK. Got 16.20.0.
Checking NPM version...
Pre requisites not met.
Errors: NPM wrong version.Got [8, 19, 4] expected 7
```
3. `invenio-cli init rdm -c v9.1 (ok)`
4. `cd my-site/`
5. `invenio-cli containers start --lock --build --setup (causes error above)`

## Expected behavior
Working Docker build
## Additional context
I tried switching various major versions of node as per https://github.com/inveniosoftware/invenio-app-rdm/issues/1981 but nothing affected that Python arch check error. Curious if this is purely not intended on M1 yet - hence my error and I should put on another arch - or if there is a fix I am missing :)

**Comment by ntarocco** [comment]
As a workaround, open your `Pipfile` and add:
```diff
[packages]
invenio-app-rdm = {extras =  ...
+ sqlalchemy[asyncio]
...
```

Delete the `Pipfile.lock`, and run `invenio-cli containers ...` again.

**Comment by steviewanders** [comment]
Thanks @ntarocco!  I'm guessing you meant for these reasons: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-install

I couldn't get that suggested syntax to work
```toml
[packages]
invenio-app-rdm = {extras = ["postgresql", "opensearch2", "sqlalchemy[asyncio]"], version = "~=11.0.0"}
```

as ran into 

`pipenv.vendor.requirementslib.exceptions.RequirementError: Failed parsing requirement from 'invenio-app-rdm[opensearch2,postgresql,sqlalchemy[asyncio]]~=11.0.0'`

which makes sense ofc but I couldn't find the Pipfile spec to fix it properly so...

so I did 

```toml
[packages]
invenio-app-rdm = {extras = ["postgresql", "opensearch2"], version = "~=11.0.0"}
sqlalchemy = {extras = ["asyncio"]}
```

whichs seemingly worked.

Cheers
