### ISSUE TITLE
REST API: Update a request with no bod result in 500 err

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-app-rdm#2702]
Package version (if known): <version>

## Steps to Reproduce
1. PUT `{{baseURL}}/api/requests/{{request_id}}`
2. Do not provide JSON body, set it as None in Postman

## Screenshots (if applicable)
logs:
<details><summary>response log</summary>
```log

Traceback (most recent call last):
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/invenio_requests/resources/requests/resource.py", line 113, in update
    item = self.service.update(
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/invenio_records_resources/services/uow.py", line 376, in inner
    res = f(self, *args, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/invenio_requests/services/requests/service.py", line 170, in update
    data, _ = schema.load(
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/invenio_records_resources/services/records/schema.py", line 90, in load
    valid_data = self.schema(context=context, **schema_args).load(data)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/marshmallow/schema.py", line 851, in _do_load
    processed_data = self._invoke_load_processors(
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/marshmallow/schema.py", line 1094, in _invoke_load_processors
    data = self._invoke_processors(
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/marshmallow/schema.py", line 1224, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/home/samk13/.pyenv/versions/3.9.19/envs/test-install/lib/python3.9/site-packages/invenio_records_resources/services/records/schema.py", line 42, in clean
    data.pop(name, None)
AttributeError: 'NoneType' object has no attribute 'pop'


```
</details>
## Additional context
I am not sure if this is out dated warning or not: https://inveniordm.docs.cern.ch/reference/rest_api_requests/#update-a-request

**Comment by beta134** [comment]
> Package version (if known): V12rc2
> 
> ## Describe the bug
> Sending Update a request without a JSON body results in a 500 error.
> 
> ## Steps to Reproduce
> 1. PUT `{{baseURL}}/api/requests/{{request_id}}`
> 2. Do not provide JSON body, set it as None in Postman
> 3. See error
> 
> ## Expected behavior
> ## Screenshots (if applicable)
> logs:
> 
> response log

25
