### ISSUE TITLE
Frontend assets build has warnings about invalid calculations

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#2718]
Package version: 12.0.0rc2

## Describe the bug
The webpack build for the frontend assets issues warnings about an invalid calculation (`auto + 5%`).

It seems like the warning stems from the variable `@mobileWidth` being set to `auto` per default.
The value is being used in a calculation in the [RDM theme](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides#L126).

## Additional context

The last few pieces of output during `invenio-cli assets build` (or `invenio-cli install`)
```
assets by path js/ 6.36 MiB
  assets by path js/*.js 6.27 MiB 116 assets
  assets by path js/skins/ 95.7 KiB
    asset js/skins/ui/oxide/skin.min.css 74.1 KiB [emitted] [from: node_modules/tinymce/skins/ui/oxide/skin.min.css] [copied] [minimized]
    + 2 assets
assets by path fonts/ 5.96 MiB
  assets by status 4.56 MiB [big] 12 assets
  assets by path fonts/*.woff2 843 KiB 7 assets
  + 9 assets
assets by path css/*.css 1.68 MiB
  assets by chunk 1.5 MiB (id hint: vendors)
    asset css/3526.ebfca715a344462c473d.css 1.46 MiB [emitted] [immutable] [minimized] [big] (id hint: vendors) 1 related asset
    asset css/1995.cea34c489e1f30826f1c.css 44.6 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
  + 10 assets
orphan modules 8.23 MiB (javascript) 5.96 MiB (asset) 10.3 KiB (runtime) [orphan] 1207 modules
runtime modules 7.43 KiB 14 modules
built modules 13.7 MiB (javascript) 2.69 MiB (css/mini-extract) [built]
  modules by path ./node_modules/ 11.2 MiB (javascript) 2.5 MiB (css/mini-extract) 884 modules
  modules by path ./js/ 2.17 MiB 174 modules
  modules by path ./scss/ 450 bytes (javascript) 189 KiB (css/mini-extract) 18 modules
  modules by path ./translations/ 284 KiB 5 modules
  modules by path ./less/invenio_app_rdm/previewer/*.less 50 bytes (javascript) 317 bytes (css/mini-extract)
    ./less/invenio_app_rdm/previewer/iiif_simple.less 50 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./less/invenio_app_rdm/previewer/iiif_simple.less 317 bytes [built] [code generated]
  modules by path ./templates/ 320 bytes
    ./templates/custom_fields/ lazy ^\.\/.*\.js$ namespace object 160 bytes [built] [code generated]
    ./templates/ eager ^\.\/.*$ namespace object 160 bytes [built] [code generated]
  + 6 modules
  

WARNING in css/3526.2db3c7847f6afd12c25c.css
css/3526.2db3c7847f6afd12c25c.css from Css Minimizer plugin
postcss-calc:: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto + 5%
^..^ webpack://./less/invenio_app_rdm/theme/elements/container.overrides:112:6
Warning: css/3526.2db3c7847f6afd12c25c.css from Css Minimizer plugin
postcss-calc:: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto + 5%
^..^ webpack://./less/invenio_app_rdm/theme/elements/container.overrides:112:6
    at CssMinimizerPlugin.buildWarning (/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/var/instance/assets/node_modules/css-minimizer-webpack-plugin/dist/index.js:299:26)
    at /home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/var/instance/assets/node_modules/css-minimizer-webpack-plugin/dist/index.js:599:55

WARNING in css/3526.2db3c7847f6afd12c25c.css
css/3526.2db3c7847f6afd12c25c.css from Css Minimizer plugin
postcss-calc:: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto + 5%
^..^ webpack://./less/invenio_app_rdm/theme/elements/container.overrides:126:6
Warning: css/3526.2db3c7847f6afd12c25c.css from Css Minimizer plugin
postcss-calc:: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto + 5%
^..^ webpack://./less/invenio_app_rdm/theme/elements/container.overrides:126:6
    at CssMinimizerPlugin.buildWarning (/home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/var/instance/assets/node_modules/css-minimizer-webpack-plugin/dist/index.js:299:26)
    at /home/mmoser/.local/share/virtualenvs/my-site-OggevyoG/var/instance/assets/node_modules/css-minimizer-webpack-plugin/dist/index.js:599:55

webpack 5.92.1 compiled with 2 warnings in 74453 ms
Built webpack project.
Dependencies installed successfully.
```

**Comment by Samk13** [comment]
Here is the answer for it: 
https://discord.com/channels/692989811736182844/704625518552547329/1221127604656930886
