### ISSUE TITLE
Guest access request: viewing request timeline UI as owner fails

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#2779]
Package version (if known): v12.0.0

## Describe the bug
When a *guest* requests access to a record with restricted files and I (as the record owner) accept the request, the timeline/detail page for the request fails to render for me (as the record owner).

E.g. after accepting the access request, visiting `https://localhost:5000/me/requests/c26b945c-b0ab-4246-ae10-88b094c0c862#` fails with the following stack trace:

```
127.0.0.1 - - [06/Aug/2024 22:21:41] "GET /me/requests/c26b945c-b0ab-4246-ae10-88b094c0c862 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoser/rdm/modules/invenio-requests/invenio_requests/views/decorators.py", line 30, in view
    return f(**kwargs)
           ^^^^^^^^^^^
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.12/site-packages/invenio_app_rdm/requests_ui/views/requests.py", line 179, in user_dashboard_request_view
    record = topic["record"]  # None when draft
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'record'
```

## Steps to Reproduce
1. Create record with restricted files
2. Visit the record's landing page via another browser or incognito tab
3. Create a guest access request
4. Accept the access request as the record owner
5. See the 500 page

**Comment by max-moser** [comment]
The values of some relevant variables in the Werkzeug Debugger:
```python
>>> request
<invenio_requests.services.requests.results.RequestItem object at 0x789c861b0140>
>>> request.data
{'id': 'c26b945c-b0ab-4246-ae10-88b094c0c862', 'created': '2024-08-06T17:22:32.944858+00:00', 'updated': '2024-08-06T20:13:04.994666+00:00', 'links': {'actions': {}, 'self': 'https://localhost:5000/api/requests/c26b945c-b0ab-4246-ae10-88b094c0c  , 'self_html': 'https://localhost:5000/me/requests/c26b945c-b0ab-4246-ae10-88b094c0c8, 'comments': 'https://localhost:5000/api/requests/c26b945c-b0ab-4246-ae10-88b094c0c, }, }
>>> request['topic']
{'record': 'f8kp2-xda53'}
>>> request['receiver']
{'user': '2'}
>>> request._obj.topic
<RDMRecordProxy {'record': 'f8kp2-xda53'} (None)>
>>> request._obj.topic.resolve()
invenio_rdm_records.records.api.RDMRecord({'id': 'f8kp2-xda53', 'pid': {'pk': 122588, 'status': 'R', 'obj_type': 'rec', 'pid_type': 'recid'}, 'pids': {'doi': {'client': 'datacite', 'provider': 'datacite', 'identifier': '10.70124/f8kp2-xda53'}, 'oai': {'provider': 'oai', 'identifier': 'oai:test.researchdata.tuwien.ac.at:f8kp2-xda53'}}, 'files': {'enabled': True},   })
>>> topic
{'permissions': {}, 'record_ui': None}
```

**Comment by Samk13** [comment]
I can reproduce this as well:

When accessing restricted files from the user side, you will also encounter a 500 error.

Steps to reproduce:

1. Create a public community.
2. Publish a record in the community with restricted files.
3. Navigate to the share option and enable "Request Access."
4. Open the record in an incognito window.
5. Request access and provide an email address.
6. Copy the verification code from the console.
7. As the owner, accept the access request.
8. Notice the error on the owner's UI when attempting to visit the request page as you described above.
9. From the guest user side, observe that the files are not opening and a 500 error appears in the logs.

<details>
<summary>logs</summary>
<code>
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/storage/base.py", line 115, in send_file
    fp = self.open(mode="rb")
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/storage/pyfs.py", line 59, in open
    fs, path = self._get_fs(create_dir=create_dir)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/storage/pyfs.py", line 46, in _get_fs
    opendir(filedir, writeable=True, create=create_dir),
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/fs/opener/registry.py", line 220, in open_fs
    _fs, _path = self.open(
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/fs/opener/registry.py", line 177, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/fs/opener/osfs.py", line 40, in open_fs
    osfs = OSFS(path, create=create)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/fs/osfs.py", line 141, in __init__
    raise errors.CreateFailed(message)
fs.errors.CreateFailed: root path '/home/user/.pyenv/versions/3.9.19/envs/v12-install/var/instance/data/62/53/3068-a923-4f71-9477-b308c338fd20' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_communities/communities/resources/resource.py", line 125, in read_logo
    return item.send_file(restricted=is_restricted)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_records_resources/services/files/results.py", line 48, in send_file
    return self._file.object_version.send_file(
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/models.py", line 1116, in send_file
    return self.file.send_file(
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/models.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/models.py", line 916, in send_file
    return self.storage(**kwargs).send_file(
  File "/home/user/.pyenv/versions/3.9.19/envs/v12-install/lib/python3.9/site-packages/invenio_files_rest/storage/base.py", line 117, in send_file
    raise StorageError("Could not send file: {}".format(e))
invenio_files_rest.errors.StorageError: 500 Internal Server Error: None
127.0.0.1 - - [12/Aug/2024 22:54:14] "GET /api/communities/dcdd6192-fe2a-4ffa-aa95-2664f07e93df/logo HTTP/1.1" 500 -
</code>
</details>
