### ISSUE TITLE
API: Invalid resource type gives a generic 500 error instead of a meaningful error message

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#897]
Package version (if known): 5.0.0.dev0

## Describe the bug
Trying to create a draft by uploading metadata with an invalid `resource_type` via the REST API property results in a generic 500 error.
The draft is not created and the user does not know what exactly went wrong.

## Steps to Reproduce
1. Upload the invalid metadata via the REST API
2. See the 500 error

## Expected behavior

The draft should be created with the invalid metadata, but the publish action should fail with a relevant validation error.

## Additional context

Server logs/stack trace:
```
127.0.0.1 - - [11/Jun/2021 14:37:54] "POST /api/records HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/werkzeug/middleware/dispatcher.py", line 66, in __call__
    return app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records_resources/resources/records/resource.py", line 82, in create
    item = self.service.create(
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_drafts_resources/services/records/service.py", line 209, in create
    return self._create(
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records_resources/services/records/service.py", line 263, in _create
    record.commit()
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records/api.py", line 452, in commit
    e.pre_commit(self, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records/systemfields/base.py", line 332, in pre_commit
    self._run('pre_commit', *args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records/systemfields/base.py", line 252, in _run
    getattr(field, method)(*args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records/systemfields/relations/field.py", line 75, in pre_commit
    record.relations.validate()
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records/systemfields/relations/mapping.py", line 58, in validate
    getattr(self, name).validate()
  File "/home/mmoser/.local/share/virtualenvs/invenio-dev-COtZPY9Q/lib/python3.8/site-packages/invenio_records/systemfields/relations/results.py", line 47, in validate
    raise InvalidRelationValue(f'Invalid value {val}.')
invenio_records.systemfields.relations.errors.InvalidRelationValue: Invalid value publication-invalid.
```

Example metadata json:
```
{
  "files": {
    "enabled": false
  },
  "metadata": {
    "resource_type": {
      "id": "publication-invalid"
    },
    "title": "Test Record",
    "description": "A record with invalid resource-type",
    "creators": [
      {
        "person_or_org": {
          "given_name": "Max",
          "family_name": "Moser",
          "type": "personal"
        },
        "affiliations": [
          {
            "name": "TU Wien",
            "identifiers": [
              {
                "scheme": "ror",
                "identifier": "04d836q62"
              }
            ]
          }
        ]
      }
    ],
    "publisher": "TU Data",
    "publication_date": "2020-12-01"
  }
}
```

**Comment by lnielsen** [comment]
Fixed
